services:
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    # restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      TZ: "Asia/Tokyo"
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.jp
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "8080:80"
    restart: always

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/workspace
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
volumes:
  db-data:
    name: postgres-data