# Generated by Django 5.0.2 on 2024-02-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='hls_path',
            field=models.CharField(blank=True, max_length=255, verbose_name='HLSパス'),
        ),
    ]
