# Generated by Django 5.0.2 on 2024-02-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_alter_video_hls_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='hls_path',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='HLSファイル'),
        ),
    ]
