# Generated by Django 5.0.2 on 2024-02-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employee_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='empno',
            field=models.PositiveIntegerField(default=0, unique=True, verbose_name='従業者番号'),
        ),
    ]
