# Generated by Django 5.0.2 on 2024-02-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_employee_empno'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='birth_day',
            field=models.DateField(blank=True, null=True, verbose_name='生年月日'),
        ),
    ]
